### ISSUE TITLE
Get PNG images [Not an issue]

### ISSUE THREAD

**Issue by Positive07** [btmills/geopattern#10]
Close this after you have read it, it is not an issue with your lib at all.

I just wanted to say that I made a script that allows you to save a pattern as a PNG image, I hosted it in [jsfiddle](http://jsfiddle.net/Positive07/Na6X5/236/)

Currently I use this when SVG images are not supported, this way I can generate the PNG image and use it in my projects... You may want to link to the script or not, just pointing out the possibility.

**Comment by anissen** [comment]
Great idea! This would definitely come in handy for me :+1:

**Comment by btmills** [comment]
This is great! I tried a different approach to this a while back, but it never worked well across every browser. @Positive07 would it be okay with you if I integrated your approach directly into the demo page?

**Comment by Positive07** [comment]
Please, do so! I'm really happy with the results your lib has given to some of my work, so I'm totally fine with this

**Comment by btmills** [comment]
@Positive07 this is live on the demo page now :ship: Thanks for showing me how to do it, and I'm glad you're finding this useful! :fireworks:

**Comment by Positive07** [comment]
Nice! I love how you did it, it merges so well with the page!
