### ISSUE TITLE
IE9 and Uint32Array

### ISSUE THREAD

**Issue by grocc** [btmills/geopattern#11]
Hello,
i have a problem with your library on IE9.
The page is not working and give back the error "'Uint32Array' is undefined".
You can see the error even in the test page (http://btmills.github.io/geopattern/).
Thanks!

**Comment by btmills** [comment]
Making GeoPattern work on IE9 isn't as difficult as I feared it might be. I added `Unit32Array` and `window.btoa()` polyfills to the demo page with 23fe2be, documented that requirement in the README with 25ecfb7, and verified that the demo page now works in IE9. @grocc let me know if you spot any issues now.

**Comment by grocc** [comment]
Perfect! Thanks for the support :)
