### ISSUE TITLE
Change Size of the generated preview images?

### ISSUE THREAD

**Issue by PDDStudio** [btmills/geopattern#15]
Is it possible to change the size of the generated preview images within the geopattern.min.js ? In case I want to generate a bigger preview before returning the Base64 encoded String.

**Comment by btmills** [comment]
The patterns are all tiling, so you should be able to repeat them to arbitrarily large dimensions. You can use [`toDataUrl()`](https://github.com/btmills/geopattern#patterntodataurl) and set that as the `background-image` for an element, then make sure the container's CSS `background-repeat` is set to `repeat`, and the background image will fill the container. Will that do the trick?

**Comment by PDDStudio** [comment]
I will try this. Actually I'm not a web developer so please give me some time to figure it out :octocat:

**Comment by btmills** [comment]
@PDDStudio were you able to try that approach?

**Comment by PDDStudio** [comment]
@btmills Not yet, I wasn't able to figure it out how to achieve it

**Comment by btmills** [comment]
@PDDStudio I'm going to close this for now, but feel free to ping back here whenever you try that!

**Comment by PDDStudio** [comment]
@btmills okay no problem, I might hit someone up with better JS knowledge than me to get it working.
