### ISSUE TITLE
Gap between repeats on Chrome

### ISSUE THREAD

**Issue by athyuttamre** [btmills/geopattern#31]
Chrome version: 57.0.2987.133 (64-bit)

I see gaps between repeated patterns in Chrome. I'm not sure if this is a browser bug or otherwise. You can test it by going to the demo site and typing "cs00".

<img width="1432" alt="screenshot 2017-04-24 23 31 21" src="https://cloud.githubusercontent.com/assets/1485350/25367797/2502aba2-2946-11e7-826d-8d0449156cec.png">

**Comment by btmills** [comment]
@athyuttamre interesting... I can't seem to get this to reproduce on any of my devices. It looks like your screenshot might be from a Retina laptop, which I don't have available for testing. Are you seeing this just in Chrome, or on other browsers as well? Can you share the output of running `GeoPattern.generate('cs00').toBase64()` in the console on the demo page? Do you have any user styles or extensions that might be applying some style rules?

**Comment by gregcarlin** [comment]
I have a retina MacBook (13") running OS X 10.12.4, also with Chrome 57.0.2987.133 (64-bit) and I don't have this problem:
<img width="1384" alt="screen shot 2017-04-27 at 11 10 00 pm" src="https://cloud.githubusercontent.com/assets/453896/25512845/ba4fb664-2b9e-11e7-93d5-dcba46aae51a.png">

**Comment by athyuttamre** [comment]
Hmm, strange; I'd seen it repeatedly for about 2 weeks, but looks like my Chrome updated to 58 today and I can't repro either. Looks like we're good!

**Comment by btmills** [comment]
Thanks @gregcarlin for the additional info and @athyuttamre for the follow-up! Hopefully this doesn't show up again and we just get to blame it on gremlins 😈

**Comment by Gaelan** [comment]
The gremlins are back, unfortunately. After upgrading to High Sierra, a user is having this issue in Chrome 62 on a 2014 13-inch retina MBP. Interestingly, it partially disappears when pinch-zoomed into; command-plus zoom has no effect, however. Frustratingly, it doesn't appear on my 2017 tbMBP.
<img width="977" alt="screen shot 2017-10-23 at 9 18 03 pm" src="https://user-images.githubusercontent.com/4495750/31924689-18a3734c-b838-11e7-8145-0ca3d5d8323a.png">
